local builtin = require('telescope.builtin')
require('telescope').load_extension("opener")
local flutter_extension = require("telescope")
flutter_extension.load_extension("flutter")
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") });
end)
vim.keymap.set('n', '<C-f>', flutter_extension.extensions.flutter.commands, {})
vim.keymap.set('n', '<leader>f', ':FlutterRun<CR>')
